//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.01 at 10:33:36 AM MST 
//


package edu.asu.spring.quadriga.domain.implementation.networks;

import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for relationEventType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="relationEventType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://digitalhps.org/creationEvents-model}creationEvent">
 *       &lt;choice maxOccurs="2" minOccurs="2">
 *         &lt;element name="relation_creator" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *         &lt;element name="relation" type="{http://digitalhps.org/creationEvents-model}RelationType"/>
 *       &lt;/choice>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "relationEventType", propOrder = {
		"relationCreatorOrRelation"
})
public class RelationEventType
extends CreationEvent
{

	@XmlElements({
		@XmlElement(name = "relation", type = RelationType.class),
		@XmlElement(name = "relation_creator", type = String.class)
	})
	protected List<Object> relationCreatorOrRelation;

	/**
	 * Gets the value of the relationCreatorOrRelation property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list,
	 * not a snapshot. Therefore any modification you make to the
	 * returned list will be present inside the JAXB object.
	 * This is why there is not a <CODE>set</CODE> method for the relationCreatorOrRelation property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * <pre>
	 *    getRelationCreatorOrRelation().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link RelationType }
	 * {@link String }
	 * 
	 * 
	 */
	public List<Object> getRelationCreatorOrRelation() {
		if (relationCreatorOrRelation == null) {
			relationCreatorOrRelation = new ArrayList<Object>();
		}
		return this.relationCreatorOrRelation;
	}

	public List<Object>  getRelation(RelationEventType re){
		List<Object> relationObjectList = new ArrayList<Object>();
		List <?> ee = re.getRelationCreatorOrRelation();
		Iterator <?> Iee=ee.iterator();
		while(Iee.hasNext()){
			Object o = Iee.next();
			if(o instanceof RelationType){
				RelationType rt = (RelationType) o;
				relationObjectList.add(rt);
			}


		}
		return relationObjectList;
	}

	public PredicateType getPredicateType(RelationType rt){
		PredicateType  predicate = null;
		List<JAXBElement<?>> e3 =rt.getIdOrCreatorOrCreationDate();
		Iterator <JAXBElement<?>> I2 = e3.iterator();
		while(I2.hasNext()){
			JAXBElement<?> element = (JAXBElement<?>) I2.next();
			if(element.getValue().toString().contains("PredicateType")){
				predicate= (PredicateType) element.getValue();

			}
		}
		return predicate;
	}
	
}

