//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.01 at 10:33:36 AM MST 
//


package edu.asu.spring.quadriga.domain.network.impl;

import java.math.BigInteger;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.digitalhps.creationevents_model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ElementEvents_QNAME = new QName("http://digitalhps.org/creationEvents-model", "element_events");
    private final static QName _TermTypePrintedRepresentation_QNAME = new QName("http://digitalhps.org/creationEvents-model", "printed_representation");
    private final static QName _TermTypeId_QNAME = new QName("http://digitalhps.org/creationEvents-model", "id");
    private final static QName _TermTypeCreationDate_QNAME = new QName("http://digitalhps.org/creationEvents-model", "creation_date");
    private final static QName _TermTypeSourceReference_QNAME = new QName("http://digitalhps.org/creationEvents-model", "source_reference");
    private final static QName _TermTypeExternalRefId_QNAME = new QName("http://digitalhps.org/creationEvents-model", "external_refId");
    private final static QName _TermTypeCreationPlace_QNAME = new QName("http://digitalhps.org/creationEvents-model", "creation_place");
    private final static QName _TermTypeCertain_QNAME = new QName("http://digitalhps.org/creationEvents-model", "certain");
    private final static QName _TermTypeReferencedTerms_QNAME = new QName("http://digitalhps.org/creationEvents-model", "referenced_terms");
    private final static QName _TermTypeCreator_QNAME = new QName("http://digitalhps.org/creationEvents-model", "creator");
    private final static QName _TermTypeNormalizedRepresentation_QNAME = new QName("http://digitalhps.org/creationEvents-model", "normalized_representation");
    private final static QName _TermTypeInternalRefId_QNAME = new QName("http://digitalhps.org/creationEvents-model", "internal_refId");
    private final static QName _TermTypeInterpretation_QNAME = new QName("http://digitalhps.org/creationEvents-model", "interpretation");
    private final static QName _CreationEventInterpretationCreator_QNAME = new QName("http://digitalhps.org/creationEvents-model", "interpretation_creator");
    private final static QName _CreationEventRefId_QNAME = new QName("http://digitalhps.org/creationEvents-model", "refId");
    private final static QName _RelationTypePredicate_QNAME = new QName("http://digitalhps.org/creationEvents-model", "predicate");
    private final static QName _RelationTypeSubject_QNAME = new QName("http://digitalhps.org/creationEvents-model", "subject");
    private final static QName _RelationTypeObject_QNAME = new QName("http://digitalhps.org/creationEvents-model", "object");
    private final static QName _TermPartTypeExpression_QNAME = new QName("http://digitalhps.org/creationEvents-model", "expression");
    private final static QName _TermPartTypePosition_QNAME = new QName("http://digitalhps.org/creationEvents-model", "position");
    private final static QName _TermPartTypeNormalization_QNAME = new QName("http://digitalhps.org/creationEvents-model", "normalization");
    private final static QName _TermPartTypeFormat_QNAME = new QName("http://digitalhps.org/creationEvents-model", "format");
    private final static QName _TermPartTypeFormattedPointer_QNAME = new QName("http://digitalhps.org/creationEvents-model", "formatted_pointer");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.digitalhps.creationevents_model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SubjectObjectType }
     * 
     */
    public SubjectObjectType createSubjectObjectType() {
        return new SubjectObjectType();
    }

    /**
     * Create an instance of {@link TermType }
     * 
     */
    public TermType createTermType() {
        return new TermType();
    }

    /**
     * Create an instance of {@link ReferencedTermsType }
     * 
     */
    public ReferencedTermsType createReferencedTermsType() {
        return new ReferencedTermsType();
    }

    /**
     * Create an instance of {@link PrintedRepresentationType }
     * 
     */
    public PrintedRepresentationType createPrintedRepresentationType() {
        return new PrintedRepresentationType();
    }

    /**
     * Create an instance of {@link RelationEventType }
     * 
     */
    public RelationEventType createRelationEventType() {
        return new RelationEventType();
    }

    /**
     * Create an instance of {@link RelationType }
     * 
     */
    public RelationType createRelationType() {
        return new RelationType();
    }

    /**
     * Create an instance of {@link PredicateType }
     * 
     */
    public PredicateType createPredicateType() {
        return new PredicateType();
    }

    /**
     * Create an instance of {@link ElementEventsType }
     * 
     */
    public ElementEventsType createElementEventsType() {
        return new ElementEventsType();
    }

    /**
     * Create an instance of {@link AppellationEventType }
     * 
     */
    public AppellationEventType createAppellationEventType() {
        return new AppellationEventType();
    }

    /**
     * Create an instance of {@link TermPartType }
     * 
     */
    public TermPartType createTermPartType() {
        return new TermPartType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ElementEventsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://digitalhps.org/creationEvents-model", name = "element_events")
    public JAXBElement<ElementEventsType> createElementEvents(ElementEventsType value) {
        return new JAXBElement<ElementEventsType>(_ElementEvents_QNAME, ElementEventsType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PrintedRepresentationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://digitalhps.org/creationEvents-model", name = "printed_representation", scope = TermType.class)
    public JAXBElement<PrintedRepresentationType> createTermTypePrintedRepresentation(PrintedRepresentationType value) {
        return new JAXBElement<PrintedRepresentationType>(_TermTypePrintedRepresentation_QNAME, PrintedRepresentationType.class, TermType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://digitalhps.org/creationEvents-model", name = "id", scope = TermType.class)
    public JAXBElement<String> createTermTypeId(String value) {
        return new JAXBElement<String>(_TermTypeId_QNAME, String.class, TermType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://digitalhps.org/creationEvents-model", name = "creation_date", scope = TermType.class)
    public JAXBElement<XMLGregorianCalendar> createTermTypeCreationDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_TermTypeCreationDate_QNAME, XMLGregorianCalendar.class, TermType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://digitalhps.org/creationEvents-model", name = "source_reference", scope = TermType.class)
    public JAXBElement<String> createTermTypeSourceReference(String value) {
        return new JAXBElement<String>(_TermTypeSourceReference_QNAME, String.class, TermType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://digitalhps.org/creationEvents-model", name = "external_refId", scope = TermType.class)
    public JAXBElement<String> createTermTypeExternalRefId(String value) {
        return new JAXBElement<String>(_TermTypeExternalRefId_QNAME, String.class, TermType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://digitalhps.org/creationEvents-model", name = "creation_place", scope = TermType.class)
    public JAXBElement<String> createTermTypeCreationPlace(String value) {
        return new JAXBElement<String>(_TermTypeCreationPlace_QNAME, String.class, TermType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://digitalhps.org/creationEvents-model", name = "certain", scope = TermType.class)
    public JAXBElement<Boolean> createTermTypeCertain(Boolean value) {
        return new JAXBElement<Boolean>(_TermTypeCertain_QNAME, Boolean.class, TermType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReferencedTermsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://digitalhps.org/creationEvents-model", name = "referenced_terms", scope = TermType.class)
    public JAXBElement<ReferencedTermsType> createTermTypeReferencedTerms(ReferencedTermsType value) {
        return new JAXBElement<ReferencedTermsType>(_TermTypeReferencedTerms_QNAME, ReferencedTermsType.class, TermType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://digitalhps.org/creationEvents-model", name = "creator", scope = TermType.class)
    public JAXBElement<String> createTermTypeCreator(String value) {
        return new JAXBElement<String>(_TermTypeCreator_QNAME, String.class, TermType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://digitalhps.org/creationEvents-model", name = "normalized_representation", scope = TermType.class)
    public JAXBElement<String> createTermTypeNormalizedRepresentation(String value) {
        return new JAXBElement<String>(_TermTypeNormalizedRepresentation_QNAME, String.class, TermType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://digitalhps.org/creationEvents-model", name = "internal_refId", scope = TermType.class)
    public JAXBElement<String> createTermTypeInternalRefId(String value) {
        return new JAXBElement<String>(_TermTypeInternalRefId_QNAME, String.class, TermType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://digitalhps.org/creationEvents-model", name = "interpretation", scope = TermType.class)
    public JAXBElement<String> createTermTypeInterpretation(String value) {
        return new JAXBElement<String>(_TermTypeInterpretation_QNAME, String.class, TermType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://digitalhps.org/creationEvents-model", name = "interpretation_creator", scope = CreationEvent.class)
    public JAXBElement<String> createCreationEventInterpretationCreator(String value) {
        return new JAXBElement<String>(_CreationEventInterpretationCreator_QNAME, String.class, CreationEvent.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://digitalhps.org/creationEvents-model", name = "id", scope = CreationEvent.class)
    public JAXBElement<String> createCreationEventId(String value) {
        return new JAXBElement<String>(_TermTypeId_QNAME, String.class, CreationEvent.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://digitalhps.org/creationEvents-model", name = "creation_date", scope = CreationEvent.class)
    public JAXBElement<XMLGregorianCalendar> createCreationEventCreationDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_TermTypeCreationDate_QNAME, XMLGregorianCalendar.class, CreationEvent.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://digitalhps.org/creationEvents-model", name = "source_reference", scope = CreationEvent.class)
    public JAXBElement<String> createCreationEventSourceReference(String value) {
        return new JAXBElement<String>(_TermTypeSourceReference_QNAME, String.class, CreationEvent.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://digitalhps.org/creationEvents-model", name = "creation_place", scope = CreationEvent.class)
    public JAXBElement<String> createCreationEventCreationPlace(String value) {
        return new JAXBElement<String>(_TermTypeCreationPlace_QNAME, String.class, CreationEvent.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://digitalhps.org/creationEvents-model", name = "refId", scope = CreationEvent.class)
    public JAXBElement<String> createCreationEventRefId(String value) {
        return new JAXBElement<String>(_CreationEventRefId_QNAME, String.class, CreationEvent.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://digitalhps.org/creationEvents-model", name = "creator", scope = CreationEvent.class)
    public JAXBElement<String> createCreationEventCreator(String value) {
        return new JAXBElement<String>(_TermTypeCreator_QNAME, String.class, CreationEvent.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://digitalhps.org/creationEvents-model", name = "internal_refId", scope = CreationEvent.class)
    public JAXBElement<String> createCreationEventInternalRefId(String value) {
        return new JAXBElement<String>(_TermTypeInternalRefId_QNAME, String.class, CreationEvent.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://digitalhps.org/creationEvents-model", name = "creation_date", scope = RelationType.class)
    public JAXBElement<XMLGregorianCalendar> createRelationTypeCreationDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_TermTypeCreationDate_QNAME, XMLGregorianCalendar.class, RelationType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://digitalhps.org/creationEvents-model", name = "id", scope = RelationType.class)
    public JAXBElement<String> createRelationTypeId(String value) {
        return new JAXBElement<String>(_TermTypeId_QNAME, String.class, RelationType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PredicateType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://digitalhps.org/creationEvents-model", name = "predicate", scope = RelationType.class)
    public JAXBElement<PredicateType> createRelationTypePredicate(PredicateType value) {
        return new JAXBElement<PredicateType>(_RelationTypePredicate_QNAME, PredicateType.class, RelationType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://digitalhps.org/creationEvents-model", name = "external_refId", scope = RelationType.class)
    public JAXBElement<String> createRelationTypeExternalRefId(String value) {
        return new JAXBElement<String>(_TermTypeExternalRefId_QNAME, String.class, RelationType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://digitalhps.org/creationEvents-model", name = "source_reference", scope = RelationType.class)
    public JAXBElement<String> createRelationTypeSourceReference(String value) {
        return new JAXBElement<String>(_TermTypeSourceReference_QNAME, String.class, RelationType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SubjectObjectType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://digitalhps.org/creationEvents-model", name = "subject", scope = RelationType.class)
    public JAXBElement<SubjectObjectType> createRelationTypeSubject(SubjectObjectType value) {
        return new JAXBElement<SubjectObjectType>(_RelationTypeSubject_QNAME, SubjectObjectType.class, RelationType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://digitalhps.org/creationEvents-model", name = "creation_place", scope = RelationType.class)
    public JAXBElement<String> createRelationTypeCreationPlace(String value) {
        return new JAXBElement<String>(_TermTypeCreationPlace_QNAME, String.class, RelationType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SubjectObjectType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://digitalhps.org/creationEvents-model", name = "object", scope = RelationType.class)
    public JAXBElement<SubjectObjectType> createRelationTypeObject(SubjectObjectType value) {
        return new JAXBElement<SubjectObjectType>(_RelationTypeObject_QNAME, SubjectObjectType.class, RelationType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://digitalhps.org/creationEvents-model", name = "creator", scope = RelationType.class)
    public JAXBElement<String> createRelationTypeCreator(String value) {
        return new JAXBElement<String>(_TermTypeCreator_QNAME, String.class, RelationType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://digitalhps.org/creationEvents-model", name = "internal_refId", scope = RelationType.class)
    public JAXBElement<String> createRelationTypeInternalRefId(String value) {
        return new JAXBElement<String>(_TermTypeInternalRefId_QNAME, String.class, RelationType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://digitalhps.org/creationEvents-model", name = "id", scope = TermPartType.class)
    public JAXBElement<String> createTermPartTypeId(String value) {
        return new JAXBElement<String>(_TermTypeId_QNAME, String.class, TermPartType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://digitalhps.org/creationEvents-model", name = "expression", scope = TermPartType.class)
    public JAXBElement<String> createTermPartTypeExpression(String value) {
        return new JAXBElement<String>(_TermPartTypeExpression_QNAME, String.class, TermPartType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://digitalhps.org/creationEvents-model", name = "creation_date", scope = TermPartType.class)
    public JAXBElement<XMLGregorianCalendar> createTermPartTypeCreationDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_TermTypeCreationDate_QNAME, XMLGregorianCalendar.class, TermPartType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://digitalhps.org/creationEvents-model", name = "position", scope = TermPartType.class)
    public JAXBElement<BigInteger> createTermPartTypePosition(BigInteger value) {
        return new JAXBElement<BigInteger>(_TermPartTypePosition_QNAME, BigInteger.class, TermPartType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://digitalhps.org/creationEvents-model", name = "source_reference", scope = TermPartType.class)
    public JAXBElement<String> createTermPartTypeSourceReference(String value) {
        return new JAXBElement<String>(_TermTypeSourceReference_QNAME, String.class, TermPartType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://digitalhps.org/creationEvents-model", name = "normalization", scope = TermPartType.class)
    public JAXBElement<String> createTermPartTypeNormalization(String value) {
        return new JAXBElement<String>(_TermPartTypeNormalization_QNAME, String.class, TermPartType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://digitalhps.org/creationEvents-model", name = "creation_place", scope = TermPartType.class)
    public JAXBElement<String> createTermPartTypeCreationPlace(String value) {
        return new JAXBElement<String>(_TermTypeCreationPlace_QNAME, String.class, TermPartType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://digitalhps.org/creationEvents-model", name = "format", scope = TermPartType.class)
    public JAXBElement<String> createTermPartTypeFormat(String value) {
        return new JAXBElement<String>(_TermPartTypeFormat_QNAME, String.class, TermPartType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://digitalhps.org/creationEvents-model", name = "formatted_pointer", scope = TermPartType.class)
    public JAXBElement<String> createTermPartTypeFormattedPointer(String value) {
        return new JAXBElement<String>(_TermPartTypeFormattedPointer_QNAME, String.class, TermPartType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://digitalhps.org/creationEvents-model", name = "creator", scope = TermPartType.class)
    public JAXBElement<String> createTermPartTypeCreator(String value) {
        return new JAXBElement<String>(_TermTypeCreator_QNAME, String.class, TermPartType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://digitalhps.org/creationEvents-model", name = "internal_refId", scope = TermPartType.class)
    public JAXBElement<String> createTermPartTypeInternalRefId(String value) {
        return new JAXBElement<String>(_TermTypeInternalRefId_QNAME, String.class, TermPartType.class, value);
    }

}
