//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.01 at 10:33:36 AM MST 
//


package edu.asu.spring.quadriga.domain.network.impl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for subjectObjectType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="subjectObjectType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="relation_event" type="{http://digitalhps.org/creationEvents-model}relationEventType"/>
 *         &lt;element name="appellation_event" type="{http://digitalhps.org/creationEvents-model}appellationEventType"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "subjectObjectType", propOrder = {
    "relationEvent",
    "appellationEvent"
})
public class SubjectObjectType {

    @XmlElement(name = "relation_event")
    protected RelationEventType relationEvent;
    @XmlElement(name = "appellation_event")
    protected AppellationEventType appellationEvent;

    /**
     * Gets the value of the relationEvent property.
     * 
     * @return
     *     possible object is
     *     {@link RelationEventType }
     *     
     */
    public RelationEventType getRelationEvent() {
        return relationEvent;
    }

    /**
     * Sets the value of the relationEvent property.
     * 
     * @param value
     *     allowed object is
     *     {@link RelationEventType }
     *     
     */
    public void setRelationEvent(RelationEventType value) {
        this.relationEvent = value;
    }

    /**
     * Gets the value of the appellationEvent property.
     * 
     * @return
     *     possible object is
     *     {@link AppellationEventType }
     *     
     */
    public AppellationEventType getAppellationEvent() {
        return appellationEvent;
    }

    /**
     * Sets the value of the appellationEvent property.
     * 
     * @param value
     *     allowed object is
     *     {@link AppellationEventType }
     *     
     */
    public void setAppellationEvent(AppellationEventType value) {
        this.appellationEvent = value;
    }

}
