//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.01 at 10:33:36 AM MST 
//


package edu.asu.spring.quadriga.domain.impl.networks;

import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;



/**
 * <p>Java class for appellationEventType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="appellationEventType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://digitalhps.org/creationEvents-model}creationEvent">
 *       &lt;choice maxOccurs="2">
 *         &lt;element name="term" type="{http://digitalhps.org/creationEvents-model}termType"/>
 *         &lt;element name="external_refId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/choice>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "appellationEventType")
public class AppellationEventType
    extends CreationEvent {

    @XmlElement(name = "external_refId", namespace = "http://digitalhps.org/creationEvents-model", type = String.class)
    private String externalRefI;
    
    public String getExternalRefI() {
        return externalRefI;
    }

    public void setExternalRefI(String externalRefI) {
        this.externalRefI = externalRefI;
    }

    public TermType getTermType() {
        return termType;
    }

    public void setTermType(TermType termType) {
        this.termType = termType;
    }

    @XmlElement(name = "term", namespace = "http://digitalhps.org/creationEvents-model", type = TermType.class)
    private TermType termType;

}
