//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.01 at 10:33:36 AM MST 
//


package edu.asu.spring.quadriga.domain.impl.networks;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;




/**
 * <p>Java class for elementEventsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="elementEventsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element name="relation_event" type="{http://digitalhps.org/creationEvents-model}relationEventType"/>
 *         &lt;element name="appellation_event" type="{http://digitalhps.org/creationEvents-model}appellationEventType"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "elementEventsType", propOrder = {
    "relationEventOrAppellationEvent"
})
public class ElementEventsType {

    @XmlElements({
        @XmlElement(name = "relation_event", type = RelationEventType.class),
        @XmlElement(name = "appellation_event", type = AppellationEventType.class)
    })
    protected List<CreationEvent> relationEventOrAppellationEvent;

    /**
     * Gets the value of the relationEventOrAppellationEvent property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the relationEventOrAppellationEvent property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRelationEventOrAppellationEvent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RelationEventType }
     * {@link AppellationEventType }
     * 
     * 
     */
    public List<CreationEvent> getRelationEventOrAppellationEvent() {
        if (relationEventOrAppellationEvent == null) {
            relationEventOrAppellationEvent = new ArrayList<CreationEvent>();
        }
        return this.relationEventOrAppellationEvent;
    }


}
